# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Description of what the lane does"
  lane :fetch_stats do
	message = sh("ruby ../fab.rb murat.aydin@zalando.de Ankara123 5a2e4bd85127ae68bc00071b 5a2e4eed8bfc5503194aff72")
	if message.include? "ATTENTION"
			slack(
                message: message,
                slack_url: "https://hooks.slack.com/services/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",
                default_payloads: [],
                success: false
            )
	else
			slack(
                message: message,
                slack_url: "https://hooks.slack.com/services/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",
                default_payloads: [],
                success: true
            )
	end
	
  end
end
